[package]
name = "topological-sort"
version = "0.2.2"
edition = "2018"
rust-version = "1.85.0"
description = "Performs topological sorting."
documentation = "https://docs.rs/topological-sort"
readme = "README.md"
repository = "https://github.com/gifnksm/topological-sort-rs"
license = "MIT OR Apache-2.0"

[package.metadata.cargo-sync-rdme.badge.badges]
maintenance = true
license = { link = "#license" }
crates-io = true
docs-rs = true
rust-version = true
github-actions = { workflows = "ci.yml" }
codecov = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]

[dev-dependencies]
quickcheck = "1.1.0"
quickcheck_macros = "1.2.0"

[badges]
maintenance = { status = "passively-maintained" }

[lints.clippy]
if_not_else = "warn"
invalid_upcast_comparisons = "warn"
items_after_statements = "warn"
mut_mut = "warn"
never_loop = "warn"
nonminimal_bool = "warn"
used_underscore_binding = "warn"

[lints.rust]
missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
missing_docs = "warn"
nonstandard_style = "warn"
trivial_casts = "warn"
trivial_numeric_casts = "warn"
unused = "warn"
unused_extern_crates = "warn"
unused_import_braces = "warn"
unused_qualifications = "warn"
